# Generated by Django 4.2.21 on 2025-05-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
    ]
