# Generated by Django 4.2.20 on 2025-03-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
