# Generated by Django 4.2.20 on 2025-03-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emoji',
            new_name='Emojis',
        ),
    ]
