# Generated by Django 5.0.6 on 2024-06-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='emotion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
