# Generated by Django 5.0.6 on 2024-06-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_status_emotion_alter_status_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='plain_description',
            field=models.TextField(default=''),
        ),
    ]
