# Generated by Django 5.0.6 on 2024-07-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
