# Generated by Django 5.0.6 on 2024-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_counselor',
            field=models.BooleanField(default=False),
        ),
    ]
