# Generated by Django 5.0.6 on 2024-07-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_is_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='confidence_scores',
            field=models.JSONField(default=dict),
        ),
    ]
