# Generated by Django 5.0.6 on 2024-07-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_status_confidence_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='confidence_scores',
        ),
    ]
