# Generated by Django 5.0.6 on 2024-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_status_anger_status_disgust_status_fear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='plain_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
