# Generated by Django 5.0.6 on 2024-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_status_plain_description_alter_status_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='neutral',
            field=models.FloatField(default=0),
        ),
    ]
