# Generated by Django 5.0.6 on 2024-08-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_status_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='anger_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='disgust_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='fear_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='happiness_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='neutral_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='sadness_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='surprise_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
