# Generated by Django 5.0.6 on 2024-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_status_anger_percentage_status_disgust_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
