# Generated by Django 5.0.6 on 2024-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_reason',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
