# Generated by Django 5.0.6 on 2024-08-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.TextField(),
        ),
    ]
