# Generated by Django 5.0.6 on 2024-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_data',
            field=models.JSONField(default=list),
        ),
    ]
