# Generated by Django 5.0.6 on 2024-08-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_chatsession_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
