# Generated by Django 5.0.6 on 2024-08-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_chatsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='question',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='response',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
