# Generated by Django 5.0.6 on 2024-08-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_timestamp_chatsession_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
