# Generated by Django 5.0.6 on 2024-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_userprofile_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_change_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
