# Generated by Django 5.0.6 on 2024-09-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_reply_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
    ]
