# Generated by Django 5.0.6 on 2024-09-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_reply_parent_reply_parent_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
    ]
