# Generated by Django 5.0.6 on 2024-09-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_contactus_is_replied_contactus_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
    ]
