# Generated by Django 5.0.6 on 2024-09-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_chatmessage_delete_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLTKResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No nltk downloaded', max_length=100, unique=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
