# Generated by Django 5.0.6 on 2024-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_nltkresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfanityWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_list', models.JSONField()),
            ],
        ),
    ]
