# Generated by Django 5.0.6 on 2024-09-27 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_profanityword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
