# Generated by Django 5.0.6 on 2024-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_feedback_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
    ]
