# Generated by Django 5.0.6 on 2024-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_itrc_staff',
            field=models.BooleanField(default=False),
        ),
    ]
