# Generated by Django 5.0.6 on 2024-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_feedback_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
