# Generated by Django 5.0.6 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_customuser_is_itrc_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
