# Generated by Django 5.0.6 on 2024-10-16 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='question_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_question_index', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
