# Generated by Django 5.0.6 on 2024-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_chatmessage_message_type_chatmessage_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('user', 'question')},
        ),
    ]
