# Generated by Django 5.0.6 on 2024-10-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix_image', models.TextField()),
                ('classification_report_html', models.TextField()),
                ('classification_report_csv', models.TextField()),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_result', to='main.dataset')),
            ],
        ),
    ]
