# Generated by Django 5.0.6 on 2024-10-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_performanceresult_processed_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('actual_label', models.CharField(max_length=50)),
                ('predicted_label', models.CharField(max_length=50)),
                ('anger_score', models.FloatField(blank=True, null=True)),
                ('disgust_score', models.FloatField(blank=True, null=True)),
                ('fear_score', models.FloatField(blank=True, null=True)),
                ('happiness_score', models.FloatField(blank=True, null=True)),
                ('neutral_score', models.FloatField(blank=True, null=True)),
                ('sadness_score', models.FloatField(blank=True, null=True)),
                ('surprise_score', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_analyses', to='main.dataset')),
            ],
        ),
    ]
