# Generated by Django 5.0.6 on 2024-10-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_remove_textanalysis_anger_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textanalysis',
            name='actual_label',
        ),
        migrations.RemoveField(
            model_name='textanalysis',
            name='predicted_label',
        ),
        migrations.RemoveField(
            model_name='textanalysis',
            name='text',
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
