# Generated by Django 5.0.6 on 2024-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_remove_textanalysis_actual_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('deactivated', 'Deactivated')], default='pending', max_length=20),
        ),
    ]
