# Generated by Django 5.0.6 on 2024-10-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_customuser_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireprogress',
            name='last_question_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='questionnaireprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
