# Generated by Django 5.0.6 on 2024-10-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_questionnaireprogress_last_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnaireprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
