# Generated by Django 5.0.6 on 2024-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_questionnaireprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
