# Generated by Django 5.0.6 on 2024-10-27 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_questionnaire_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='answer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
