# Generated by Django 5.0.6 on 2024-11-05 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_notificationcounselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcounselor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notifications', to='main.status'),
        ),
        migrations.AlterField(
            model_name='notificationcounselor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
