# Generated by Django 5.0.6 on 2024-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_notificationcounselor_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profanityword',
            options={'verbose_name': 'Profanity Word', 'verbose_name_plural': 'Profanity Words'},
        ),
        migrations.AlterField(
            model_name='profanityword',
            name='word_list',
            field=models.JSONField(default=list),
        ),
    ]
