# Generated by Django 5.0.6 on 2024-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_profanityword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('question', 'Question'), ('bot_message', 'Bot Message'), ('user_message', 'User Message'), ('counselor_message', 'Counselor Message')], max_length=50, null=True),
        ),
    ]
