# Generated by Django 5.0.6 on 2024-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('sub_group', models.CharField(max_length=100)),
                ('codepoints', models.CharField(max_length=255)),
            ],
        ),
    ]
