# Generated by Django 5.0.6 on 2024-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.CharField(max_length=255),
        ),
    ]
