# Generated by Django 5.0.6 on 2024-11-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_alter_emoji_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='codepoints',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='group',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='sub_group',
            field=models.TextField(null=True),
        ),
    ]
