# Generated by Django 5.0.6 on 2024-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_alter_emoji_codepoints_alter_emoji_emoji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoji',
            options={'ordering': ['sub_group']},
        ),
        migrations.AlterField(
            model_name='emoji',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
