# Generated by Django 5.0.6 on 2024-11-14 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_chatsession_counselormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'counselor', 'is_active'], name='main_chatse_user_id_1ebff8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_message_at'], name='main_chatse_last_me_250041_idx'),
        ),
        migrations.AddIndex(
            model_name='counselormessage',
            index=models.Index(fields=['chat_session', 'timestamp'], name='main_counse_chat_se_96d9ba_idx'),
        ),
    ]
