# Generated by Django 5.0.6 on 2024-11-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_notification_message_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at']},
        ),
    ]
