# Generated by Django 5.0.6 on 2024-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_chatmessage_anger_chatmessage_anger_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireprogress',
            name='emotion_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireprogress',
            name='normalized_emotions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireprogress',
            name='last_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
