# Generated by Django 5.0.6 on 2024-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('verify', 'Verify User'), ('reject', 'Reject User'), ('upload_masterlist', 'Upload Masterlist'), ('update_setting', 'Update Setting'), ('delete_user', 'Delete User')], max_length=20),
        ),
    ]
