# Generated by Django 5.0.6 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0003_alter_auditlog_action_alter_auditlog_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentmasterlist',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='enrollmentmasterlist',
            name='email',
        ),
    ]
