# Generated by Django 5.0.6 on 2024-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0007_alter_auditlog_action_alter_sessionlog_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentmasterlist',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='masterlists/'),
        ),
        migrations.AddField(
            model_name='enrollmentmasterlist',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollmentmasterlist',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
