# Generated by Django 5.0.6 on 2024-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0008_enrollmentmasterlist_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
