# Generated by Django 5.0.6 on 2024-10-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0009_auditlog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrollmentmasterlist',
            name='csv_file',
        ),
        migrations.RemoveField(
            model_name='enrollmentmasterlist',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='enrollmentmasterlist',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
