# Generated by Django 5.0.6 on 2024-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0011_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='auto_accept_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='auto_reject_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
