# Generated by Django 5.0.6 on 2024-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0012_systemsetting_auto_accept_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('auto_accepted', 'Auto Accepted'), ('auto_rejected', 'Auto Rejected')], default='pending', max_length=15),
        ),
    ]
