# Generated by Django 5.0.6 on 2024-11-19 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrc_tools', '0014_systemsetting_is_active_alter_systemsetting_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_system',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itrc_tools_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
