# Generated by Django 5.0.6 on 2024-07-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
