INSERT INTO `main_userprofile` (`user_id`, `avatar`, `is_email_verified`, `new_email`, `email_change_requested_at`, `email_verification_requested_at`, `bio`)
VALUES
(68, '', 0, NULL, NULL, NULL, NULL),
(88, '', 0, NULL, NULL, NULL, NULL),
(72, '', 0, NULL, NULL, NULL, NULL),
(81, '', 0, NULL, NULL, NULL, NULL),
(74, '', 0, NULL, NULL, NULL, NULL),
(77, '', 0, NULL, NULL, NULL, NULL),
(70, '', 0, NULL, NULL, NULL, NULL),
(73, '', 0, NULL, NULL, NULL, NULL),
(71, '', 0, NULL, NULL, NULL, NULL),
(69, '', 0, NULL, NULL, NULL, NULL),
(11, '', 0, NULL, NULL, NULL, NULL),
(75, '', 0, NULL, NULL, NULL, NULL),
(78, '', 0, NULL, NULL, NULL, NULL),
(80, '', 0, NULL, NULL, NULL, NULL),
(79, '', 0, NULL, NULL, NULL, NULL),
(76, '', 0, NULL, NULL, NULL, NULL),
(67, '', 0, NULL, NULL, NULL, NULL),
(89, '', 0, NULL, NULL, NULL, NULL),
(7, '', 5, 0, NULL, NULL, NULL, NULL),
(8, '', 6, 0, NULL, NULL, NULL, NULL),
(12, '', 10, 0, NULL, NULL, NULL, NULL),
(13, '', 11, 0, NULL, NULL, NULL, NULL),
(14, '', 12, 0, NULL, NULL, NULL, NULL),
(15, '', 13, 0, NULL, NULL, NULL, NULL),
(16, '', 14, 0, NULL, NULL, NULL, NULL),
(17, '', 15, 0, NULL, NULL, NULL, NULL),
(22, '', 24, 0, NULL, NULL, NULL, ''),
(23, '', 25, 0, NULL, NULL, NULL, NULL),
(24, '', 26, 0, NULL, NULL, NULL, NULL),
(26, '', 30, 0, NULL, NULL, NULL, NULL),
(27, '', 32, 0, NULL, NULL, NULL, NULL),
(28, '', 33, 0, NULL, NULL, NULL, NULL),
(29, '', 36, 0, NULL, NULL, NULL, NULL),
(30, '', 37, 0, NULL, NULL, NULL, NULL),
(31, '', 38, 0, NULL, NULL, NULL, NULL),
(32, '', 39, 0, NULL, NULL, NULL, NULL),
(33, '', 40, 0, NULL, NULL, NULL, NULL),
(34, '', 41, 0, NULL, NULL, NULL, NULL),
(35, '', 42, 0, NULL, NULL, NULL, NULL),
(36, '', 43, 0, NULL, NULL, NULL, NULL),
(37, '', 44, 0, NULL, NULL, NULL, NULL),
(38, '', 45, 0, NULL, NULL, NULL, ''),
(54, '', 54, 0, NULL, NULL, NULL, NULL),
(55, '', 55, 0, NULL, NULL, NULL, NULL),
(60, '', 58, 0, NULL, NULL, NULL, NULL),
(71, '', 63, 0, NULL, NULL, NULL, NULL),
(72, '', 64, 0, NULL, NULL, NULL, NULL),
(73, '', 65, 0, NULL, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE 
`avatar` = VALUES(`avatar`), 
`is_email_verified` = VALUES(`is_email_verified`), 
`new_email` = VALUES(`new_email`), 
`email_change_requested_at` = VALUES(`email_change_requested_at`), 
`email_verification_requested_at` = VALUES(`email_verification_requested_at`), 
`bio` = VALUES(`bio`);
